# Generated by Django 3.2.16 on 2022-10-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
