# Generated by Django 3.2.16 on 2022-10-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
