# Generated by Django 3.2.16 on 2022-11-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20221104_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
